apiVersion: v1
kind: ReplicationController
metadata:
  name: sample-k8-app
spec:
  replicas: 5
  selector:
    app: sample-k8-app
  template:
    metadata:
      name: sample-k8-app
      labels:
        app: sample-k8-app
    spec:
      containers:
      - name: sample-k8-app
        image: sushshring/k8_sample
        imagePullPolicy: Always
        env:
        - name: MONGO_DB_HOSTNAME
          value: "$(MONGO_NODEPORT_SERVICE_HOST):$(MONGO_NODEPORT_SERVICE_PORT)"
        - name: MONDO_DB_NAME
          value: "sample_k8_db"
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sample-k8-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: sample-k8-app
  type: LoadBalancer
